medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      password: "1234"  
      dbname: medical_warehouse
      schema: public