version: 2

models:
  - name: dim_channels
    description: "Dimension for Telegram channels"
    columns:
      - name: channel_key
        description: "Surrogate primary key"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Unique username"
        tests:
          - not_null

  - name: dim_dates
    description: "Date dimension"
    columns:
      - name: date_key
        description: "Integer date key"
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "Fact table for messages"
    columns:
      - name: message_id
        description: "Message ID"
        tests:
          - not_null
      - name: channel_key
        description: "FK to dim_channels"
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "FK to dim_dates"
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key